runtime: python27
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    application_readable: false
    static_files: dist/mzaifquraishi/index.html
    require_matching_file: false
    upload: dist/mzaifquraishi/index.html
  - url: /(.*)
    application_readable: false
    static_files: dist/mzaifquraishi/\1
    require_matching_file: false
    upload: dist/mzaifquraishi/.*
env_variables:
  API_KEY: AIzaSyB5-ei1mxGG7cJzt0fqy0GO562gmM93W-U
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}